name: CI (Deploy)

on:
  push:
    branches: [ master, main ]
    paths-ignore: [ "docs/**", "*.md" ]

concurrency:
  group: production

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
    with:
      node-version: '20'
    secrets: inherit

  build:
    uses: ./.github/workflows/_build.yml
    with:
      node-version: '20'
    secrets: inherit

  unit-test:
    needs: [ lint, build ]
    uses: ./.github/workflows/_test.yml
    with:
      node-version: '20'
    secrets: inherit
